# GET /profile
curl http://localhost:3001/profile
# result -> {"statusCode":401,"message":"Unauthorized"}

# POST /auth/login
curl -X POST http://localhost:3001/auth/login -d '{"username": "john", "password": "changeme"}' -H "Content-Type: application/json"
# result -> {"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2Vybm... }

# GET /profile using access_token returned from previous step as bearer code
curl http://localhost:3001/profile -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOjEsImlhdCI6MTY3Nzk4MzE4MiwiZXhwIjoxNjc3OTgzMjQyfQ.AsF4mYW_5n586BGaKqaxrriVeeNkkx5Y8dZGXsnUEyo"
# result -> {"userId":1,"username":"john"}